### ISSUE TITLE
[API Proxy] Déterminer quelle(s) IP sont ban par la route de TVA

### ISSUE THREAD

**Issue by XavierJp** [annuaire-entreprises-data-gouv-fr/api-proxy#36]
Actuellement une ou plusieurs IP sont bannies par les services de vérification de la TVA

<img width="326" alt="image" src="https://github.com/user-attachments/assets/10e550a2-7e7b-4d14-b1a1-f62efad424ae">

Domaine qui nous ban : `https://ec.europa.eu/taxation_customs/vies/rest-api/ms/FR/vat/`
Machine : api-proxy en production 

La machine de proxy faisant de la rotation d'IP, il faut déterminer quelle est l'IP problématique. (Curl verbose?)

**Comment by ad2ien** [comment]
La PR permet de load balancer seulement le trafic venant de docker. On peut utiliser `make debug-banned-ip-tva` pour tester une requête tva provenant de chaque ip. Résultat toutes les ips retournent un 200 et les données 🤔

**Comment by ad2ien** [comment]
La PR https://github.com/annuaire-entreprises-data-gouv-fr/infrastructure/pull/279  permet de load balancer seulement le trafic venant de docker. On peut utiliser `make debug-banned-ip-tva` pour tester une requête tva provenant de chaque ip. Résultat toutes les ips retournent un 200 et les données 🤔

**Comment by ad2ien** [comment]
Après des modifs pour afficher toute la réponse, IP trouvée! Prochaine étape : l'échanger avec une IP de staging...

**Comment by ad2ien** [comment]
Petite note, à faire le soir : 
- [ ] dans OVH : affecter une ip de staging à la prod
- [ ] dans l'infra : échanger ip staging et ip bloquée
- [ ] configurer le server de prod
- [ ] dans ovh : affecter l'ip bloquée à staging 
- [ ] configurer staging
